name: Install Python and required modules
#on: [push, pull_request]
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the pdf branch
  push:
    branches: [ pdf ]
  pull_request:
    branches: [ pdf ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt 
    - run: |
        python downloads/add_to_content_htm_2a.py
        python downloads/add_to_content_htm_2b.py
        python downloads/generate_pages.py
